apiVersion: apps/v1
kind: Deployment
metadata:
  name: reliant-scrape-deployment
spec:
  selector:
    matchLabels:
      app: reliant-scrape
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: reliant-scrape
    spec:
      containers:
      - name: reliant-scrape
        image: stevenhurwitt/reliant-scrape:ubuntu
        ports:
        - containerPort: 80